language: python

python:
  - "2.7"

install:
  - (cd vendor && git submodule update --init --recursive)
  - pip install -r requirements/compiled.txt
  - cp webpagemaker/settings/local.py-dist webpagemaker/settings/local.py
  - mysql -e 'create database playdoh_app;'
  - python manage.py syncdb --noinput
  - python manage.py migrate --noinput

script: make test
